In [1]:

#Import numpy
import numpy as np

#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

#Salaries
KobeBryant_Salary = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
JoeJohnson_Salary = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
LeBronJames_Salary = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
CarmeloAnthony_Salary = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
DwightHoward_Salary = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
ChrisBosh_Salary = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
ChrisPaul_Salary = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDurant_Salary = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
DerrickRose_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
DwayneWade_Salary = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary, KevinDurant_Salary, DerrickRose_Salary, DwayneWade_Salary])

#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

#Minutes Played
KobeBryant_MP = [3277,3140,3192,2960,2835,2779,2232,3013,177,1207]
JoeJohnson_MP = [3340,2359,3343,3124,2886,2554,2127,2642,2575,2791]
LeBronJames_MP = [3361,3190,3027,3054,2966,3063,2326,2877,2902,2493]
CarmeloAnthony_MP = [2941,2486,2806,2277,2634,2751,1876,2482,2982,1428]
DwightHoward_MP = [3021,3023,3088,2821,2843,2935,2070,2722,2396,1223]
ChrisBosh_MP = [2751,2658,2425,2928,2526,2795,2007,2454,2531,1556]
ChrisPaul_MP = [2808,2353,3006,3002,1712,2880,2181,2335,2171,2857]
KevinDurant_MP = [1255,1255,2768,2885,3239,3038,2546,3119,3122,913]
DerrickRose_MP = [1168,1168,1168,3000,2871,3026,1375,0,311,1530]
DwayneWade_MP = [2892,1931,1954,3048,2792,2823,1625,2391,1775,1971]
#Matrix
MinutesPlayed = np.array([KobeBryant_MP, JoeJohnson_MP, LeBronJames_MP, CarmeloAnthony_MP, DwightHoward_MP, ChrisBosh_MP, ChrisPaul_MP, KevinDurant_MP, DerrickRose_MP, DwayneWade_MP])

#Field Goals
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])

#Field Goal Attempts
KobeBryant_FGA = [2173,1757,1690,1712,1569,1639,1336,1595,73,713]
JoeJohnson_FGA = [1395,1139,1497,1420,1386,1161,931,1052,1018,1025]
LeBronJames_FGA = [1823,1621,1642,1613,1528,1485,1169,1354,1353,1279]
CarmeloAnthony_FGA = [1572,1453,1481,1207,1502,1503,1025,1489,1643,806]
DwightHoward_FGA = [881,873,974,979,834,1044,726,813,800,423]
ChrisBosh_FGA = [1087,1094,1027,1263,1158,1056,807,907,953,745]
ChrisPaul_FGA = [947,871,1291,1255,637,928,890,856,870,1170]
KevinDurant_FGA = [647,647,1366,1390,1668,1538,1297,1433,1688,467]
DerrickRose_FGA = [436,436,436,1208,1373,1597,695,0,164,835]
DwayneWade_FGA = [1413,962,937,1739,1511,1384,837,1093,761,1084]
#Matrix
FieldGoalAttempts = np.array([KobeBryant_FGA, JoeJohnson_FGA, LeBronJames_FGA, CarmeloAnthony_FGA, DwightHoward_FGA, ChrisBosh_FGA, ChrisPaul_FGA, KevinDurant_FGA, DerrickRose_FGA, DwayneWade_FGA])

#Points
KobeBryant_PTS = [2832,2430,2323,2201,1970,2078,1616,2133,83,782]
JoeJohnson_PTS = [1653,1426,1779,1688,1619,1312,1129,1170,1245,1154]
LeBronJames_PTS = [2478,2132,2250,2304,2258,2111,1683,2036,2089,1743]
CarmeloAnthony_PTS = [2122,1881,1978,1504,1943,1970,1245,1920,2112,966]
DwightHoward_PTS = [1292,1443,1695,1624,1503,1784,1113,1296,1297,646]
ChrisBosh_PTS = [1572,1561,1496,1746,1678,1438,1025,1232,1281,928]
ChrisPaul_PTS = [1258,1104,1684,1781,841,1268,1189,1186,1185,1564]
KevinDurant_PTS = [903,903,1624,1871,2472,2161,1850,2280,2593,686]
DerrickRose_PTS = [597,597,597,1361,1619,2026,852,0,159,904]
DwayneWade_PTS = [2040,1397,1254,2386,2045,1941,1082,1463,1028,1331]
#Matrix
Points = np.array([KobeBryant_PTS, JoeJohnson_PTS, LeBronJames_PTS, CarmeloAnthony_PTS, DwightHoward_PTS, ChrisBosh_PTS, ChrisPaul_PTS, KevinDurant_PTS, DerrickRose_PTS, DwayneWade_PTS])      

In [2]:
Points

array([[2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133,   83,  782],
       [1653, 1426, 1779, 1688, 1619, 1312, 1129, 1170, 1245, 1154],
       [2478, 2132, 2250, 2304, 2258, 2111, 1683, 2036, 2089, 1743],
       [2122, 1881, 1978, 1504, 1943, 1970, 1245, 1920, 2112,  966],
       [1292, 1443, 1695, 1624, 1503, 1784, 1113, 1296, 1297,  646],
       [1572, 1561, 1496, 1746, 1678, 1438, 1025, 1232, 1281,  928],
       [1258, 1104, 1684, 1781,  841, 1268, 1189, 1186, 1185, 1564],
       [ 903,  903, 1624, 1871, 2472, 2161, 1850, 2280, 2593,  686],
       [ 597,  597,  597, 1361, 1619, 2026,  852,    0,  159,  904],
       [2040, 1397, 1254, 2386, 2045, 1941, 1082, 1463, 1028, 1331]])

In [9]:
Salary

array([[15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
        25244493, 27849149, 30453805, 23500000],
       [12000000, 12744189, 13488377, 14232567, 14976754, 16324500,
        18038573, 19752645, 21466718, 23180790],
       [ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
        18518574, 19450000, 22407474, 22458000],
       [ 4493160,  4806720,  6061274, 13758000, 15202590, 16647180,
        18091770, 19536360, 20513178, 21436271],
       [ 3348000,  4235220, 12455000, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
        16359805, 17779458, 18668431, 20068563],
       [       0,        0,  4171200,  4484040,  4796880,  6053663,
        15506632, 16669630, 17832627, 18995624],
       [       0,        0,        0,  4822800,  5184480,  55461

In [4]:
r1=["I","AM","HAPPY"]
r2=["WHAT","A","DAY"]
r3=[1,2,3]
[r1,r2,r3]

[['I', 'AM', 'HAPPY'], ['WHAT', 'A', 'DAY'], [1, 2, 3]]

In [5]:
np.array([r1,r2,r3])

array([['I', 'AM', 'HAPPY'],
       ['WHAT', 'A', 'DAY'],
       ['1', '2', '3']], dtype='<U5')

In [7]:
print(np.array([r1,r2,r3]))

[['I' 'AM' 'HAPPY']
 ['WHAT' 'A' 'DAY']
 ['1' '2' '3']]


In [8]:
Games[0]

array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35])

In [9]:
Games[2]

array([79, 78, 75, 81, 76, 79, 62, 76, 77, 69])

In [7]:
Games[2][0]

79

In [11]:
Games[2][-1]

69

In [14]:
Games[2][::-1]

array([69, 77, 76, 62, 79, 76, 81, 75, 78, 79])

In [16]:
Games[2,9]

69

In [17]:
#--------dictionary

In [27]:
dict1={"key1":"val1", "key2":"val2", "key3":"val3"}

In [30]:
dict1["key2"]

'val2'

In [32]:
dict2={"Germany":"i have been there","France":2, "Spain":True}

In [34]:
dict2["France"]

2

In [37]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [40]:
Games[Pdict["KobeBryant"]]#pdict foi setado como dicionario la em cima, ele retorna o numero da linha correspondente ao nome do jogador

array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35])

In [43]:
Games[Pdict["KobeBryant"],Sdict["2012"]]

78

In [45]:
Points[Pdict["DerrickRose"],Sdict["2010"]]

2026

In [46]:
#----matrix operation

In [10]:
FieldGoals/Games#o erro aparece porque dividiu por 0

C:\Users\Gustavo\Anaconda31\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[12.225     , 10.55844156,  9.45121951,  9.75609756,  9.80821918,
         9.02439024,  9.89655172,  9.46153846,  5.16666667,  7.6       ],
       [ 7.70731707,  9.40350877,  7.8902439 ,  7.84810127,  8.35526316,
         7.13888889,  7.05      ,  6.18055556,  5.84810127,  5.575     ],
       [11.07594937,  9.8974359 , 10.58666667,  9.74074074, 10.10526316,
         9.59493671, 10.01612903, 10.06578947,  9.96103896,  9.04347826],
       [ 9.45      , 10.63076923,  9.45454545,  8.10606061,  9.97101449,
         8.88311688,  8.01818182,  9.98507463,  9.64935065,  8.95      ],
       [ 5.70731707,  6.41463415,  7.1097561 ,  7.08860759,  6.2195122 ,
         7.93589744,  7.7037037 ,  6.18421053,  6.66197183,  6.12195122],
       [ 7.84285714,  7.86956522,  7.56716418,  7.98701299,  8.57142857,
         6.80519481,  6.89473684,  6.55405405,  6.2278481 ,  7.79545455],
       [ 5.21794872,  5.953125  ,  7.875     ,  8.08974359,  6.97777778,
         5.375     ,  7.08333333,  5.88571429

In [59]:
import warnings
warnings.filterwarnings("ignore")
FieldGoals/Games

array([[12.225     , 10.55844156,  9.45121951,  9.75609756,  9.80821918,
         9.02439024,  9.89655172,  9.46153846,  5.16666667,  7.6       ],
       [ 7.70731707,  9.40350877,  7.8902439 ,  7.84810127,  8.35526316,
         7.13888889,  7.05      ,  6.18055556,  5.84810127,  5.575     ],
       [11.07594937,  9.8974359 , 10.58666667,  9.74074074, 10.10526316,
         9.59493671, 10.01612903, 10.06578947,  9.96103896,  9.04347826],
       [ 9.45      , 10.63076923,  9.45454545,  8.10606061,  9.97101449,
         8.88311688,  8.01818182,  9.98507463,  9.64935065,  8.95      ],
       [ 5.70731707,  6.41463415,  7.1097561 ,  7.08860759,  6.2195122 ,
         7.93589744,  7.7037037 ,  6.18421053,  6.66197183,  6.12195122],
       [ 7.84285714,  7.86956522,  7.56716418,  7.98701299,  8.57142857,
         6.80519481,  6.89473684,  6.55405405,  6.2278481 ,  7.79545455],
       [ 5.21794872,  5.953125  ,  7.875     ,  8.08974359,  6.97777778,
         5.375     ,  7.08333333,  5.88571429

In [67]:
FieldGoalsPerGame = np.matrix.round(FieldGoals/Games,2)
FieldGoalsPerGame

array([[12.22, 10.56,  9.45,  9.76,  9.81,  9.02,  9.9 ,  9.46,  5.17,
         7.6 ],
       [ 7.71,  9.4 ,  7.89,  7.85,  8.36,  7.14,  7.05,  6.18,  5.85,
         5.58],
       [11.08,  9.9 , 10.59,  9.74, 10.11,  9.59, 10.02, 10.07,  9.96,
         9.04],
       [ 9.45, 10.63,  9.45,  8.11,  9.97,  8.88,  8.02,  9.99,  9.65,
         8.95],
       [ 5.71,  6.41,  7.11,  7.09,  6.22,  7.94,  7.7 ,  6.18,  6.66,
         6.12],
       [ 7.84,  7.87,  7.57,  7.99,  8.57,  6.81,  6.89,  6.55,  6.23,
         7.8 ],
       [ 5.22,  5.95,  7.88,  8.09,  6.98,  5.38,  7.08,  5.89,  6.55,
         6.93],
       [ 8.74,  8.74,  7.34,  8.93,  9.68,  9.12,  9.74,  9.02, 10.48,
         8.81],
       [ 5.2 ,  5.2 ,  5.2 ,  7.09,  8.62,  8.78,  7.74,   nan,  5.8 ,
         6.63],
       [ 9.32,  9.25,  8.61, 10.81,  9.34,  9.11,  8.49,  8.25,  7.69,
         8.21]])

In [68]:
FieldGoalsPerGame[Pdict["DerrickRose"],Sdict["2011"]]

7.74

In [69]:
FieldGoalsPerGame = np.matrix.round(MinutesPlayed/Games,2)
FieldGoalsPerGame

array([[40.96, 40.78, 38.93, 36.1 , 38.84, 33.89, 38.48, 38.63, 29.5 ,
        34.49],
       [40.73, 41.39, 40.77, 39.54, 37.97, 35.47, 35.45, 36.69, 32.59,
        34.89],
       [42.54, 40.9 , 40.36, 37.7 , 39.03, 38.77, 37.52, 37.86, 37.69,
        36.13],
       [36.76, 38.25, 36.44, 34.5 , 38.17, 35.73, 34.11, 37.04, 38.73,
        35.7 ],
       [36.84, 36.87, 37.66, 35.71, 34.67, 37.63, 38.33, 35.82, 33.75,
        29.83],
       [39.3 , 38.52, 36.19, 38.03, 36.09, 36.3 , 35.21, 33.16, 32.04,
        35.36],
       [36.  , 36.77, 37.58, 38.49, 38.04, 36.  , 36.35, 33.36, 35.02,
        34.84],
       [35.86, 35.86, 34.6 , 38.99, 39.5 , 38.95, 38.58, 38.51, 38.54,
        33.81],
       [29.2 , 29.2 , 29.2 , 37.04, 36.81, 37.36, 35.26,   nan, 31.1 ,
        30.  ],
       [38.56, 37.86, 38.31, 38.58, 36.26, 37.14, 33.16, 34.65, 32.87,
        31.79]])